services:
  - type: web
    name: github-portfolio-analyzer-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: MISTRAL_MODEL
        value: mistral-small
